server.port=8085


spring.application.name=consultation-service


spring.datasource.url=jdbc:h2:mem:consultationDB
spring.datasource.driver-class-name=org.h2.Driver


spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


rendezvous.service.url=http://localhost:8084


api.gateway.url=http://localhost:8080


eureka.client.service-url.defaultZone=http://localhost:8761/eureka
